# Generated by Django 3.0.6 on 2020-05-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_title', models.CharField(max_length=150)),
                ('long_title', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=4)),
                ('image', models.ImageField(upload_to='movieimg')),
            ],
        ),
    ]
