# Generated by Django 3.0.6 on 2020-05-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedisp', '0004_auto_20200506_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='title',
            field=models.CharField(default='', max_length=40),
        ),
    ]
