# Generated by Django 3.0.6 on 2020-05-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedisp', '0005_movie_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='title',
        ),
        migrations.AlterField(
            model_name='movie',
            name='short_title',
            field=models.CharField(max_length=25),
        ),
    ]
