# Generated by Django 3.0.6 on 2020-05-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedisp', '0006_auto_20200506_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='title',
            field=models.CharField(default='', max_length=150),
        ),
    ]
