# Generated by Django 3.0.6 on 2020-05-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedisp', '0007_movie_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='top_movie',
            field=models.BooleanField(default=True),
        ),
    ]
