# Generated by Django 3.0.6 on 2020-05-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedisp', '0008_movie_top_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.CharField(default='', max_length=200),
        ),
    ]
