# Generated by Django 3.0.6 on 2020-05-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedisp', '0009_movie_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='half_rating',
            field=models.BooleanField(default=False),
        ),
    ]
